name: FlorHTR
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - editdistance=0.6.0
  - kaldiio=2.17.2
  - opencv
  - tensorflow
  - tqdm=4.64.0
  - pip
  - fastparquet
  - pyarrow
  - yaml
  - numpy
  - pandas