name: FlorHTR
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - editdistance
  - kaldiio
  - opencv>=2.6
  - symspellpy
  - tensorflow-gpu=2.6.0
  - tqdm
  - pip
  - fastparquet
  - pyarrow
  - yaml
  - h5py
  - numpy
  - pandas
  - matplotlib