import os
import re
import copy
import time
import dotenv
import openai
import concurrent


class SpellChecker():
    """
    Check and correct spelling errors in texts using the OpenAI API.
    """

    def __init__(self, api_key=None, env_key=None, dotenv_file='.env'):
        """
        Constructs the necessary attributes for the class object.

        Parameters
        ----------
        api_key : str
            The API key to interact with the OpenAI API.
        env_key : str
            The key to access the environment variable which holds the API key.
        dotenv_file : str
            The file name of the environment file. Default is '.env'.
        """

        self.api_key = api_key
        self.env_key = env_key

        self.base_path = os.path.join(os.path.dirname(__file__), '..')
        self.dotenv_path = os.path.join(self.base_path, dotenv_file)

        if self.env_key is not None:
            dotenv.load_dotenv(self.dotenv_path)
            self.api_key = os.environ[self.env_key]

        # https://platform.openai.com/account/api-keys
        openai.api_key = self.api_key

    def enhance_texts(self, texts, instruction=None):
        """
        Enhances texts by correcting spelling errors.

        Parameters
        ----------
        texts : list
            The texts to be enhanced.
        instruction : str, optional
            The instruction to be followed by the API.

        Returns
        -------
        enhanced_texts : list
            The enhanced texts.
        """

        tokens_length = 0
        batches = [[]]

        for i, text in enumerate(texts):
            for j, line in enumerate(text):
                pp_text = f'<{i}.{j}>{line}</{i}.{j}>'
                pp_text_tokens_length = len(pp_text.split())

                if tokens_length + pp_text_tokens_length > 1024:
                    batches.append([])
                    tokens_length = 0
                else:
                    tokens_length += pp_text_tokens_length

                batches[-1].append(pp_text)

        print(f"Total batches: {len(batches)}")

        with concurrent.futures.ProcessPoolExecutor() as executor:
            futures = [executor.submit(self._request_api, instruction, ' '.join(x)) for x in batches]
            enhanced_batches = [future.result() for future in futures]

        enhanced_texts = copy.deepcopy(texts)
        pattern = re.compile(r'<([0-9]+\.[0-9]+)>(.*?)<\/\1>', re.DOTALL)

        for enhanced_batch in enhanced_batches:
            matches = pattern.findall(enhanced_batch)

            for match in matches:
                tag = match[0].split('.')
                enhanced_texts[int(tag[0])][int(tag[1])] = match[1].replace('\n', '').strip()

        return enhanced_texts

    def _request_api(self, instruction=None, prompt=None):
        """
        Makes a request to the OpenAI API.

        Parameters
        ----------
        instruction : str, optional
            The instruction to be followed by the API.
        prompt : str, optional
            The prompt for the API.

        Returns
        -------
        response : str
            The API response.
        """

        if instruction is None:
            instruction = """
                Proofread the sentences and correct the spelling errors generated by a handwriting recognition system.
            """

        retry_limit = 10
        retry_sleep = 10
        retry_count = 0

        while retry_count < retry_limit:
            try:
                response = openai.Edit.create(engine='text-davinci-edit-001',
                                              instruction=' '.join(instruction.split()),
                                              input=prompt or '',
                                              temperature=0,
                                              top_p=1,
                                              n=1)

                response = response.choices[0].text.strip()
                return response

            except Exception as err:
                retry_count += 1
                print(err)
                print(f"Request failed. Retrying... (Attempt {retry_count}/{retry_limit})")

                retry_sleep += 5
                time.sleep(retry_sleep)

        return prompt
